Repository voyages-sncf-technologies/hesperides, pull requests merged in 2018-07, with the labels that each got.

#275 Feature/hideplatformmodules
  core/pom.xml
  core/presentation/src/main/java/org/hesperides/presentation/controllers/PlatformsController.java
  core/presentation/src/main/java/org/hesperides/presentation/io/platforms/ApplicationOutput.java
  core/presentation/src/main/java/org/hesperides/presentation/io/platforms/PlatformOutput.java
Labels: us platforms, v4

#288 deploy release on tags
  .travis.yml
Labels: indus, v4

#291 Fix Mongo Configuration : use distinct names for beans
  bootstrap/src/main/resources/application-mongo.yml
  core/infrastructure/src/main/java/org/hesperides/core/infrastructure/mongo/MongoProjectionRepositoryConfiguration.java
  core/infrastructure/src/main/java/org/hesperides/core/infrastructure/mongo/eventstores/AxonMongoEventStoreConfiguration.java
Labels: bug, v4

#300 discover tags using branch name
  .travis.yml
Labels: indus, v4
