Repository voyages-sncf-technologies/hesperides, pull requests merged in 2018-06, with the labels that each got.

#218 Feature/graphite
  bootstrap/src/main/resources/application-graphite.yaml
  domain/src/main/java/org/hesperides/domain/Profiles.java
  infrastructure/pom.xml
  infrastructure/src/main/java/org/hesperides/infrastructure/graphite/MetricsConfiguration.java
Labels: indus, v4

#217 Feature/remote mongo
  bootstrap/src/main/resources/application-mongo.yml
  bootstrap/src/main/resources/application.yml
  bootstrap/src/main/resources/banner.txt
  documentation/postman/hesperides.postman_collection.json
  documentation/postman/hesperides_local.postman_environment.json
  infrastructure/src/main/java/org/hesperides/infrastructure/mongo/FakeMongoProjectionRepositoryConfiguration.java
  infrastructure/src/main/java/org/hesperides/infrastructure/mongo/MongoConfiguration.java
  infrastructure/src/main/java/org/hesperides/infrastructure/mongo/MongoProjectionRepositoryConfiguration.java
  infrastructure/src/main/java/org/hesperides/infrastructure/mongo/eventstores/AxonMongoEventStoreConfiguration.java
  infrastructure/src/main/java/org/hesperides/infrastructure/mongo/eventstores/FakeAxonMongoEventStoreConfiguration.java
  presentation/src/main/java/org/hesperides/presentation/PresentationConfiguration.java
  presentation/src/main/java/org/hesperides/presentation/controllers/TechnosController.java
  presentation/src/main/java/org/hesperides/presentation/io/PartialTemplateIO.java
  tests/bdd/src/test/java/org/hesperides/tests/bdd/modules/contexts/TemplateContext.java
  tests/bdd/src/test/java/org/hesperides/tests/bdd/modules/scenarios/GetATemplate.java
  tests/bdd/src/test/java/org/hesperides/tests/bdd/technos/scenarios/RetrieveATemplate.java
  tests/bdd/src/test/resources/moduleTemplates.feature
Labels: v4

#220 Docker doc
  docker/docker-compose-graphite.yml
  docker/docker-compose-mongo.yml
  documentation/docker/docker.md
Labels: v4

#226 prepare next snapshot version (0.0.3-SNAPSHOT)
  application/pom.xml
  bootstrap/pom.xml
  domain/pom.xml
  infrastructure/pom.xml
  pom.xml
  presentation/pom.xml
  tests/bdd/pom.xml
  tests/integration/pom.xml
  tests/tech/pom.xml
Labels: indus, v4

#227 Release Hesperides v0.0.3
  application/pom.xml
  bootstrap/pom.xml
  domain/pom.xml
  infrastructure/pom.xml
  pom.xml
  presentation/pom.xml
  tests/bdd/pom.xml
  tests/integration/pom.xml
  tests/tech/pom.xml
Labels: indus, v4

#228 prepare next snapshot version (0.0.4-SNAPSHOT)
  application/pom.xml
  bootstrap/pom.xml
  domain/pom.xml
  infrastructure/pom.xml
  pom.xml
  presentation/pom.xml
  tests/bdd/pom.xml
  tests/integration/pom.xml
  tests/tech/pom.xml
Labels: indus, v4

#242 Ajout scope test sur spring-boot-starter-test
  application/pom.xml
  presentation/pom.xml
Labels: bug, v4

#249 Implémentation interface Comparable pour PropertyOutput
  bootstrap/src/main/resources/application-mongo.yml
  infrastructure/src/main/java/org/hesperides/infrastructure/mongo/MongoConfiguration.java
  infrastructure/src/main/java/org/hesperides/infrastructure/mongo/MongoProjectionRepositoryConfiguration.java
  infrastructure/src/main/java/org/hesperides/infrastructure/mongo/eventstores/AxonMongoEventStoreConfiguration.java
  presentation/src/main/java/org/hesperides/presentation/io/templatecontainers/PropertyOutput.java
Labels: enhancement, v4

#254 Release Hesperides v0.0.4
  application/pom.xml
  bootstrap/pom.xml
  domain/pom.xml
  infrastructure/pom.xml
  pom.xml
  presentation/pom.xml
  tests/bdd/pom.xml
  tests/integration/pom.xml
  tests/tech/pom.xml
Labels: indus, v4

#262 Issue #234 and #233
  application/src/main/java/org/hesperides/application/platforms/PlatformUseCases.java
  domain/src/main/java/org/hesperides/domain/platforms/PlatformProjectionRepository.java
  domain/src/main/java/org/hesperides/domain/platforms/commands/PlatformAggregate.java
  domain/src/main/java/org/hesperides/domain/platforms/commands/PlatformCommands.java
  domain/src/main/java/org/hesperides/domain/platforms/entities/Platform.java
  domain/src/main/kotlin/org/hesperides/domain/platforms/Platform.kt
  infrastructure/src/main/java/org/hesperides/infrastructure/mongo/platforms/MongoPlatformProjectionRepository.java
  infrastructure/src/main/java/org/hesperides/infrastructure/mongo/platforms/MongoPlatformRepository.java
  infrastructure/src/main/java/org/hesperides/infrastructure/mongo/platforms/documents/PlatformDocument.java
  infrastructure/src/main/java/org/hesperides/infrastructure/mongo/platforms/documents/PlatformKeyDocument.java
  presentation/src/main/java/org/hesperides/presentation/controllers/PlatformsController.java
  presentation/src/main/java/org/hesperides/presentation/io/platforms/PlatformIO.java
  tests/bdd/src/test/java/org/hesperides/tests/bdd/platforms/contexts/PlatformContext.java
  tests/bdd/src/test/java/org/hesperides/tests/bdd/platforms/scenarios/CreateAPlatform.java
  tests/bdd/src/test/resources/platforms.feature
Labels: v4
