Repository voyages-sncf-technologies/hesperides, pull requests merged in 2018-05, with the labels that each got.

#186 Feature sba
  README.md
  bootstrap/src/main/resources/application-sba.yml
  bootstrap/src/main/resources/application.yml
  domain/src/main/java/org/hesperides/domain/Profiles.java
  infrastructure/pom.xml
  infrastructure/src/main/java/org/hesperides/infrastructure/springbootadmin/SpringBootAdminConfiguration.java
  pom.xml
Labels: indus, v4

#187 Gestion des logs via yaml
  .travis.yml
  bootstrap/src/main/resources/application.yml
  bootstrap/src/main/resources/logback-spring.xml
  bootstrap/src/main/resources/logback.xml
Labels: indus, v4

#189 Deploy snapshot
  .travis.yml
  .travis/codesigning.asc.enc
  .travis/deploy-settings.xml
  pom.xml
Labels: indus, v4

#196 Release Hesperides v0.0.1
  application/pom.xml
  bootstrap/pom.xml
  domain/pom.xml
  infrastructure/pom.xml
  pom.xml
  presentation/pom.xml
  tests/bdd/pom.xml
  tests/integration/pom.xml
  tests/tech/pom.xml
Labels: release, v4

#201 Feature/javadoc sources
  application/pom.xml
  bootstrap/pom.xml
  domain/pom.xml
  infrastructure/pom.xml
  pom.xml
  presentation/pom.xml
  tests/bdd/pom.xml
  tests/integration/pom.xml
  tests/tech/pom.xml
Labels: indus, v4

#205 Update & Delete Template dans techno
  application/src/main/java/org/hesperides/application/technos/TechnoUseCases.java
  domain/src/main/java/org/hesperides/domain/modules/commands/ModuleAggregate.java
  domain/src/main/java/org/hesperides/domain/technos/TechnoProjectionRepository.java
  domain/src/main/java/org/hesperides/domain/technos/commands/TechnoAggregate.java
  domain/src/main/java/org/hesperides/domain/technos/commands/TechnoCommands.java
  domain/src/main/kotlin/org/hesperides/domain/technos/Techno.kt
  infrastructure/src/main/java/org/hesperides/infrastructure/mongo/technos/MongoTechnoProjectionRepository.java
  infrastructure/src/main/java/org/hesperides/infrastructure/mongo/technos/TechnoDocument.java
  presentation/src/main/java/org/hesperides/presentation/controllers/TechnoController.java
Labels: v4
